# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.7.6
  maturin_version: ">=1.1.0,<2"
  python_min: ${{ python_min }}.*

recipe:
  name: granian
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/granian/granian-${{ version }}.tar.gz
  sha256: 5e36d28b947b2c18bc7dc61072b3aa67c28b28d871f55a4daabea8eb6300e50e

build:
  number: 0
  skip: not (match(python, python_min) and is_abi3 == 'true')

outputs:
  - package:
      name: granian
    build:
      script:
        - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
        - |-
          {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        version_independent: true
        entry_points:
          - granian = granian:cli.cli
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - maturin ${{ maturin_version }}
        - if: unix
          then:
            # for the jemalloc-sys crate
            - make
      host:
        - pip
        - python
        - python-abi3
        - maturin >=1.1.0,<2
        - if: unix
          then:
            - jemalloc
      run:
        - python
        - click >=8.0.0
        - if: unix
          then:
            - uvloop >=0.18.0
      run_constraints:
        - setproctitle >=1.3.3,<1.4
        - watchfiles >=0.21,<2.0
    tests:
      - python:
          python_version: ${{ python_min }}
          pip_check: true
          imports: granian
      - requirements:
          run:
            - pip
        script:
          - pip check
          - granian --help

  - package:
      name: granian-with-pname
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("granian", upper_bound="x.x.x") }}
        - setproctitle
    tests:
      - python:
          python_version: ${{ python_min }}
          pip_check: true
          imports: granian
      - requirements:
          run:
            - pip
        script:
          - pip check
          - granian --help

  - package:
      name: granian-with-reload
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("granian", upper_bound="x.x.x") }}
        - watchfiles
    tests:
      - python:
          python_version: ${{ python_min }}
          pip_check: true
          imports: granian
      - requirements:
          run:
            - pip
        script:
          - pip check
          - granian --help

  - package:
      name: granian-with-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("granian", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("granian-with-pname", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("granian-with-reload", upper_bound="x.x.x") }}
    tests:
      - python:
          python_version: ${{ python_min }}
          pip_check: true
          imports: granian
      - files:
          source:
            - tests/
        requirements:
          run:
            - httpx >=0.25.0,<0.26
            - pip
            - pytest >=7.4.2,<7.5
            - pytest-asyncio >=0.21.1,<0.22
            - websockets
            - sniffio >=1.3,<2
        script:
          - pip check
          - granian --help
          - pytest -vv --tb=long --color=yes -k "not (test_reject or (test_rsgi and test_body_stream_req) or (test_scope and workers))"

about:
  homepage: https://github.com/emmett-framework/granian
  summary: A Rust HTTP server for Python applications
  repository: https://github.com/emmett-framework/granian
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  feedstock-name: granian
  recipe-maintainers:
    - thewchan
    - bollwyvl
